import './globals.css'

import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import { ThemeProvider } from 'next-themes'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const sora = Sora({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={sora.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
